(require :lispbuilder-sdl)
(require :scelisp)
(in-package :scelisp)

(defun init ()
  (sce-init-interface 0 0))
(defun quit ()
  (sce-quit-interface))
(defun draw ())

(defun run ()
  (sdl:with-init ()
    (sdl:window 200 200 :opengl t)
    (setf (sdl:frame-rate) 15)
    (init)
    (sdl:with-events ()
      (:quit-event () t)
      (:idle ()
        (draw)
        (sdl:update-display)))
    (quit)))